### ISSUE TITLE
Result for deeplabv2

### ISSUE THREAD

**Issue by linyq2117** [shjo-april/RecurSeed_and_EdgePredictMix#3]
Thanks for your impressive work.

It seems that you provide results on both deeplabv2 and deeplabv3+ in paper v1 but only deeplabv3+ result remained in paper v2. Could you provide the latest results on deeplabv2 (which most previous works adpoted) or share the code and training details of deeplabv3+ ?

**Comment by shjo-april** [comment]
I agree with your point. I updated DeepLabv2 experiments. Have a good day!
