### ISSUE TITLE
Pseudo labels for segmentation experiments

### ISSUE THREAD

**Issue by qazwsx042** [shjo-april/RecurSeed_and_EdgePredictMix#4]
Hi @OFRIN,  could you please provide pseudo labels (e.g., for VOC train-aug data) used in segmentation experiments?  
We just  want to test them on  existing  deeplabV2 models. Thanks :)

**Comment by shjo-april** [comment]
I just updated pseudo labels and DeepLabv2 experiments. Have a good day!
